on:
  - push

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install node dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run build
      - name: Run headless browser test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm test
